name: workflow-example
on:
  push:
    branches:
      - master

jobs:
  simple-db2:
    runs-on: ubuntu-latest
    steps:
      - name: start db2 container
        run: docker run --name mydb2 --privileged=true -e LICENSE=accept -e DBNAME=testdb -dt ibmcom/db2

      - name: wait database create
        uses: amanoese/db2-container-wait-action@v1

      - name: check connect database
        run: docker exec -t mydb2 bash -c "sudo -i -u db2inst1 db2 'connect to testdb'"

